# For testing routes with VSCode REST Client Extension

POST http://localhost:4000/entries/create
Content-Type: application/json

{
    "mood": 5,
    "notes": "lorem ipsum",
    "timestamp": 1642948330679
}

###

DELETE http://localhost:4000/entries/2

###

POST http://localhost:4000/entries/update
Content-Type: application/json

{
    "mood": 3,
    "notes": "new notes",
    "timestamp": 1642948330679,
    "id": 5
}

// "id": 3

###

GET http://localhost:4000/entries/list
